name: ${project.name}
version: ${project.version}
description: CheatBreaker API plugin
author: CheatBreaker Development Team
website: https://cheatbreaker.com
main: com.cheatbreaker.api.CheatBreakerApi